using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Razorpay.Api;
using SmartEmergency.API.DTOs;

namespace SmartEmergency.API.Controllers
{
    [Authorize]
    [ApiController]
    [Route("api/[controller]")]
    public class PaymentController : ControllerBase
    {
        private readonly IConfiguration _configuration;
        private readonly SmartEmergency.API.Data.ApplicationDbContext _context;

        public PaymentController(IConfiguration configuration, SmartEmergency.API.Data.ApplicationDbContext context)
        {
            _configuration = configuration;
            _context = context;
        }

        [HttpPost("create-order")]
        public IActionResult CreateOrder([FromBody] PaymentRequestDto request)
        {

            string key = _configuration["Razorpay:KeyId"];
            string secret = _configuration["Razorpay:KeySecret"];

            if (string.IsNullOrEmpty(key) || key.Contains("YOUR_KEY"))
            {

                return BadRequest("Razorpay keys are not configured.");

            }

            try
            {

                RazorpayClient client = new RazorpayClient(key, secret);

                Dictionary<string, object> options = new Dictionary<string, object>();

                options.Add("amount", request.Amount * 100); // Amount in paise

                options.Add("currency", "INR");

                options.Add("receipt", "order_rcptid_" + request.BookingId);

                options.Add("payment_capture", 1); // Auto capture

                Order order = client.Order.Create(options);

                string orderId = order["id"].ToString();

                return Ok(new { orderId = orderId, key = key });

            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error creating order: {ex.Message}");
            }
        }

        [HttpPost("verify-payment")]
        public ActionResult VerifyPayment([FromBody] PaymentVerificationDto dto)
        {
            try
            {
                // In a real scenario, you verify the signature generated by Razorpay
                // string generatedSignature = Utils.generateSignature(dto.RazorpayOrderId, dto.RazorpayPaymentId, secret);
                // if (generatedSignature != dto.RazorpaySignature) return BadRequest("Invalid signature");

                // For this implementation, we trust the flow for "Test Mode" simplicity
                // Update booking status

                var booking = _context.Bookings.Find(dto.BookingId);

                if (booking == null) return NotFound("Booking not found");


                booking.IsPaid = true;

                booking.PaymentId = dto.RazorpayPaymentId;

                _context.SaveChanges();


                return Ok("Payment verified and booking updated.");
            }
            catch (Exception ex)
            {

                return StatusCode(500, $"Error verifying payment: {ex.Message}");

            }
        }
    }
}
